const products = [
    {
        product_id: 1,
        name: 'Organic Apples',
        description: 'Fresh organic apples from the farm.',
        price: 3.99,
        stock: 100,
        image_url: 'https://example.com/images/apples.jpg',
        category: 'fruits',
    },
    {
        product_id: 2,
        name: 'Bananas',
        description: 'Sweet and ripe bananas, perfect for snacks.',
        price: 0.99,
        stock: 200,
        image_url: 'https://example.com/images/bananas.jpg',
        category: 'fruits',
    },
    {
        product_id: 3,
        name: 'Strawberries',
        description: 'Fresh, juicy strawberries for desserts or snacking.',
        price: 5.49,
        stock: 150,
        image_url: 'https://example.com/images/strawberries.jpg',
        category: 'fruits',
    },
    {
        product_id: 4,
        name: 'Carrots',
        description: 'Crunchy and sweet farm-grown carrots.',
        price: 1.49,
        stock: 300,
        image_url: 'https://example.com/images/carrots.jpg',
        category: 'vegetables',
    },
    {
        product_id: 5,
        name: 'Broccoli',
        description: 'Freshly harvested broccoli for healthy meals.',
        price: 2.49,
        stock: 120,
        image_url: 'https://example.com/images/broccoli.jpg',
        category: 'vegetables',
    },
    {
        product_id: 6,
        name: 'Red Potatoes',
        description: 'Freshly harvested red potatoes.',
        price: 2.29,
        stock: 250,
        image_url: 'https://example.com/images/potatoes.jpg',
        category: 'vegetables',
    },
    {
        product_id: 7,
        name: 'Tomatoes',
        description: 'Ripe and flavorful tomatoes for salads or cooking.',
        price: 2.99,
        stock: 180,
        image_url: 'https://example.com/images/tomatoes.jpg',
        category: 'vegetables',
    },
    {
        product_id: 8,
        name: 'Cucumbers',
        description: 'Crisp cucumbers, great for salads or snacks.',
        price: 1.89,
        stock: 220,
        image_url: 'https://example.com/images/cucumbers.jpg',
        category: 'vegetables',
    },
    {
        product_id: 9,
        name: 'Free-Range Eggs',
        description: 'A dozen free-range chicken eggs.',
        price: 4.5,
        stock: 200,
        image_url: 'https://example.com/images/eggs.jpg',
        category: 'other',
    },
    {
        product_id: 10,
        name: 'Raw Honey',
        description: 'Unprocessed raw honey from local beekeepers.',
        price: 8.99,
        stock: 50,
        image_url: 'https://example.com/images/honey.jpg',
        category: 'other',
    },
    {
        product_id: 11,
        name: 'Whole Milk',
        description: 'Fresh whole milk from grass-fed cows.',
        price: 2.99,
        stock: 150,
        image_url: 'https://example.com/images/milk.jpg',
        category: 'other',
    },
    {
        product_id: 12,
        name: 'Herbal Tea',
        description: 'Dried herbal tea leaves for a soothing brew.',
        price: 5.99,
        stock: 120,
        image_url: 'https://example.com/images/tea.jpg',
        category: 'other',
    },
    {
        product_id: 13,
        name: 'Farm Butter',
        description: 'Rich and creamy handmade farm butter.',
        price: 3.49,
        stock: 80,
        image_url: 'https://example.com/images/butter.jpg',
        category: 'other',
    },
    {
        product_id: 14,
        name: 'Cheddar Cheese',
        description: 'Sharp and flavorful aged cheddar cheese.',
        price: 6.99,
        stock: 70,
        image_url: 'https://example.com/images/cheese.jpg',
        category: 'other',
    },
    {
        product_id: 15,
        name: 'Orange Juice',
        description: 'Freshly squeezed orange juice, no additives.',
        price: 4.99,
        stock: 100,
        image_url: 'https://example.com/images/orange_juice.jpg',
        category: 'other',
    },
    {
        product_id: 16,
        name: 'Spinach',
        description: 'Fresh and nutrient-rich spinach leaves.',
        price: 1.99,
        stock: 140,
        image_url: 'https://example.com/images/spinach.jpg',
        category: 'vegetables',
    },
    {
        product_id: 17,
        name: 'Blueberries',
        description: 'Sweet and tangy blueberries, great for desserts.',
        price: 5.99,
        stock: 90,
        image_url: 'https://example.com/images/blueberries.jpg',
        category: 'fruits',
    },
    {
        product_id: 18,
        name: 'Avocados',
        description: 'Creamy and delicious avocados, perfect for guacamole.',
        price: 1.69,
        stock: 130,
        image_url: 'https://example.com/images/avocados.jpg',
        category: 'fruits',
    },
];

export { products };
